#!/usr/bin/python2

############################################
# Imports
############################################
import logging
import argparse
import subprocess as sp
import os, sys
import json
import gtk, glib
import urlparse, urllib

#import threading
#import time
#import json
#import gtk, glib
#import signal


############################################
# Logging
############################################

# log = logging.getLogger(__name__)
log = logging.getLogger()

def _init_log():
    FORMAT = '%(module)s %(funcName)s:%(lineno)d %(message)s'
    # logging.basicConfig(format=FORMAT)
    log.setLevel(logging.INFO)
    # log.setLevel(logging.DEBUG)
    h = logging.StreamHandler()
    # f = MyFormatter()
    f = logging.Formatter(FORMAT)
    h.setFormatter(f)
    log.addHandler(h)

_init_log()

############################################
# Argument parsing
############################################
scale_types = ['fit', 'cover', 'auto', 'manual']
gravity_types = ['center']

desc = '''Wallpaper configurator'''
p = argparse.ArgumentParser(description=desc)
p.add_argument("--debug", help="debug mode", action="store_true")
p.add_argument("--scale", help="scale type: " + ','.join(scale_types) + \
               "(default %(default)s)",
    choices=scale_types, default='auto')
p.add_argument("--gravity", help="gravity type: " + ','.join(gravity_types) + \
               "(default %(default)s)",
    choices=gravity_types, default='center')
p.add_argument("--scale-r", help="scale ration, default %(default)s",
               metavar='ratio', default=1.0)
p.add_argument("--color", help="fill color, name or '#RRGGBB' value (default %(default)s)",
    default='#ffd2ac')
p.add_argument("--saved", help="apply saved configuration (if any) and exit",
    action='store_true')

p.add_argument("image", help="image", nargs='?')


args = p.parse_args()
if args.debug:
    log.setLevel(logging.DEBUG)

log.debug("Args: %s", args)

############################################
# Misc
############################################
def die(msg, ret = 1):
    print >> sys.stderr, msg
    exit(ret)

############################################
# Thumbnail Image
############################################

def get_geom(
        base_ratio, base_width, base_height,
        pix_ratio, pix_width, pix_height,
        scale_type, scale_ratio,
        gravity):
    
    log.debug("ratio: base %s, pix %s", base_ratio, pix_ratio)
    log.debug("scale: type %s, ratio %s", scale_type, scale_ratio)
    log.debug("base size %d x %d", base_width, base_height)
    log.debug("pix size %d x %d", pix_width, pix_height)
        
    if scale_type == 'auto':
        diff = abs(base_ratio - pix_ratio)
        log.debug("diff ratio %.2f", diff)
        if diff < 0.55:
            scale_type_real = 'cover'
        else:
            scale_type_real = 'fit'
    else:
        scale_type_real = scale_type

    if scale_type_real == 'cover':
        scale_ratio = max(float(base_width) / pix_width,
                          float(base_height) / pix_height)
    elif scale_type_real == 'fit':
        scale_ratio = min(float(base_width) / pix_width,
                          float(base_height) / pix_height)
    elif scale_type_real == 'manual':
        if scale_ratio <= 0.0:
            scale_ratio = 0.05
    else:
        scale_ratio = 0.2


    log.debug("scale: type %s, ratio %.2f", scale_type_real, scale_ratio)
    dest_width  = max(10, pix_width * scale_ratio)
    dest_height = max(10, pix_height * scale_ratio)
    if scale_type_real == 'manual':
        while True:
            log.debug("dest size %s x %s", dest_width, dest_height)

            if dest_width < 3000 and dest_height < 3000:
                break
            scale_ratio -= 0.05
            if scale_ratio <= 0:
                break
            dest_width  = max(10, pix_width * scale_ratio)
            dest_height = max(10, pix_height * scale_ratio)
                
    if scale_ratio <= 0.0:
        scale_ratio = 0.05

    dest_x = 0
    dest_y = 0
    offset_x = 0.0
    offset_y = 0.0
    
    if gravity == 'center':
        offset_x = (base_width - dest_width) / 2
        offset_y = (base_height - dest_height) / 2

        if offset_x > 0:
            dest_x = offset_x
        if offset_y > 0:
            dest_y = offset_y

    log.debug("offset %+d%+d", int(offset_x), int(offset_y))
    if dest_width > base_width:
        dest_width = base_width
    if dest_height > base_height:
        dest_height = base_height
    log.debug("dest geom=%dx%d pos=%dx%d",
        dest_width, dest_height, dest_x, dest_y)

    dest_x = int(dest_x)
    dest_y = int(dest_y)
    dest_width = int(dest_width)
    dest_height = int(dest_height)
    offset_x = int(offset_x)
    offset_y = int(offset_y)
    return (dest_x, dest_y, dest_width, dest_height,
            offset_x, offset_y, scale_type_real, scale_ratio)


        
class ThImage(gtk.Image):
  
    def __init__(self):
        gtk.Image.__init__(self)
        self.connect("expose_event", self._expose)
        self.connect("size_allocate", self._size_alloc)
        self.pix = None
        self.ipix = None
        self.color = None
        self.uri = None
        self.idle_id = None
        self.scale = 'auto'
        self.scale_real = None
        self.scale_r = 1.0
        self.gravity = 'center'
        self.set_color("#ffd2ac")
        self.sratio = gtk.gdk.screen_width() / float(gtk.gdk.screen_height())

        
    def set_pix(self, uri):
        log.debug("uri %s", uri)
        self.uri = None
        self.ipix = None
        self._update_pix()
        
        if not uri:
            return None
        
        if uri.startswith('file://'):
            uri = urllib.url2pathname(uri[7:])
        elif uri[0] == '/':
            pass
        else:
            log.warning("not a path %s", uri)
            return None
      
        try:
            self.ipix = gtk.gdk.pixbuf_new_from_file(uri)
            self.uri = uri
            return uri
        except:
            return None


    def set_color(self, color):
        log.debug("color %s", color)
        self.color = str(color)
        self.rgba = self._color_to_rgba(self.color)
        self._update_pix()

        
    def set_gravity_type(self, gravity):
        log.debug("gravity %s", gravity)
        if not gravity in gravity_types:
            log.warning("unsupported gravity %s", gravity)
            return
        self.gravity = gravity
        self._update_pix()

        
   
    def set_scale_type(self, scale):
        log.debug("scale %s", scale)
        if not scale in scale_types:
            log.warning("unsupported scale %s", scale)
            return
        self.scale = scale
        self._update_pix()

        
    def set_scale_ratio(self, scale_r):
        log.debug("scale ratio %s", scale_r)
        if self.scale == 'manual':
            log.debug("accepted")
            self.scale_r = scale_r
        self._update_pix()

        
    def get_scale_ratio(self):
        return self.scale_r
    
        
    def get_conf(self):
        c = {
            'scale': self.scale_real,
            'scale_r': self.scale_r,
            'color': self.color,
            'image': self.uri,
            'gravity': self.gravity,
        }
        return c
    
    def _expose(self, widget, event):
        a = event.area
        log.debug("ev %s, pix %s", a, self.pix)
        if not self.pix:
            self._update_pix()
        else:
            self.window.draw_pixbuf(self.style.black_gc, self.pix, 0, 0, a.x, a.y)


    def _size_alloc(self, widget, a):
        log.debug("%s, ratio %f", a, float(a.width) / a.height)
        self.pix = None
        self._update_pix()


    def _update_pix(self):
        log.debug("idle %s", self.idle_id)
        if self.idle_id:
            return
        self.idle_id = glib.idle_add(self._update_pix_real)


    def _color_to_rgba(self, color):
        c = gtk.gdk.color_parse(color)
        rgba = ((c.red >> 8) << 24) | ((c.green >> 8) << 16) | ((c.blue >> 8) << 8)
        # rgba = 0xffd2ac00
        log.debug("rgba %x", rgba)
        return rgba


    def _compose_ipix(self):
        pw = self.ipix.get_width()
        ph = self.ipix.get_height()
        pr = 1.0 * pw / ph
        t = get_geom(self.sratio, self.pix.get_width(), self.pix.get_height(),
                     pr, pw, ph,
                     self.scale, self.scale_r, self.gravity)
        dest_x, dest_y, dest_width, dest_height, offset_x, \
            offset_y, self.scale_real, self.scale_r = t
        self.ipix.composite(self.pix,
            dest_x, dest_y, dest_width, dest_height,
            offset_x, offset_y, self.scale_r, self.scale_r,
            gtk.gdk.INTERP_HYPER, 255)

    
    def _compose_ipix_old(self):
        log.debug("start scale: type %s, ratio %s", self.scale, self.scale_r)
        wbg = self.pix.get_width()
        hbg = self.pix.get_height()
        log.debug("bg size %d x %d", wbg, hbg)
        wpx = self.ipix.get_width()
        hpx = self.ipix.get_height()
        log.debug("ipix size %d x %d", wpx, hpx)
        
        if self.scale == 'auto':
            scale_r = wpx / float(hpx)
            diff = abs(scale_r - self.sratio)
            log.debug("ipix ratio %.2f, screen ratio %.2f, diff %.2f",
                scale_r, self.sratio, diff)
            if diff < 0.55:
                self.scale_real = 'cover'
            else:
                self.scale_real = 'fit'
        else:
            self.scale_real = self.scale

        if self.scale_real == 'cover':
            self.scale_r = max(float(wbg) / wpx, float(hbg) / hpx)
        elif self.scale_real == 'fit':
            self.scale_r = min(float(wbg) / wpx, float(hbg) / hpx)
        elif self.scale_real == 'manual':
            if self.scale_r <= 0.0:
                self.scale_r = 0.05
        else:
            self.scale_r = 0.2
        log.debug("scale: type %s, ratio %.2f", self.scale_real, self.scale_r)
        dest_width  = max(10, wpx * self.scale_r)
        dest_height = max(10, hpx * self.scale_r)
        if self.scale_real == 'manual':
            while True:
                log.debug("dest size %s x %s", dest_width, dest_height)

                if dest_width < 3000 and dest_height < 3000:
                    break
                self.scale_r -= 0.05
                if self.scale_r <= 0:
                    break
                dest_width  = max(10, wpx * self.scale_r)
                dest_height = max(10, hpx * self.scale_r)
                
        if self.scale_r <= 0:
            self.scale_r = 0.05

        dest_x = 0
        dest_y = 0
        offset_x = 0.0
        offset_y = 0.0

        if self.gravity == 'center':
            offset_x = (wbg - dest_width) / 2
            offset_y = (hbg - dest_height) / 2

            if offset_x > 0:
                dest_x = offset_x
            if offset_y > 0:
                dest_y = offset_y

        log.debug("offset %+d%+d", int(offset_x), int(offset_y))
        if dest_width > wbg:
            dest_width = wbg
        if dest_height > hbg:
            dest_height = hbg
        log.debug("dest geom=%dx%d pos=%dx%d",
            dest_width, dest_height, dest_x, dest_y)
     
        dest_x = int(dest_x)
        dest_y = int(dest_y)
        dest_width = int(dest_width)
        dest_height = int(dest_height)
        offset_x = int(offset_x)
        offset_y = int(offset_y)
        self.ipix.composite(self.pix,
            dest_x, dest_y, dest_width, dest_height,
            offset_x, offset_y, self.scale_r, self.scale_r,
            gtk.gdk.INTERP_HYPER, 255)


    def _update_pix_real(self):
        a = self.get_allocation()
        log.debug("a %s", a)
        self.pix = gtk.gdk.Pixbuf(gtk.gdk.COLORSPACE_RGB, False,
            8, a.width, a.height)
        self.pix.fill(self.rgba)
        if self.ipix:
            self._compose_ipix()
        self.queue_draw()
        self.idle_id = None
        return False

############################################
# GUI
############################################

gui = {}

def gui_exit_cb(x=None, y=None):
    exit(0)



    
def gui_draged_cb(widget, drag_context, x, y, selection, info, time):
    uri = selection.data.split()[0]
    uri = gui['th'].set_pix(uri)
    log.debug("set to %s", uri)
    gui['image'].unselect_all()
    if uri:
        gui['image'].set_filename(uri)
    

def gui_file_set_cb(btn):
    path = btn.get_filename()
    log.debug("path %s", path)
    uri = gui['th'].set_pix(path)
    log.debug("set to %s", uri)
    gui['image'].unselect_all()
    if uri:
        gui['image'].set_filename(uri)
            

    
def gui_file_unset_cb(cbtn, btn):
    log.debug("")
    btn.unselect_all()
    gui['th'].set_pix(None)
    
    
def gui_file_btn():
    hbox = gtk.HBox(False, 3)
 
    btn = gtk.FileChooserButton('Select a File')
    gui['image'] = btn
    hbox.pack_start(btn, False)
    btn.connect("file-set", gui_file_set_cb)
    btn.set_width_chars(20)
  

    f = gtk.FileFilter()
    f.set_name("Images")
    f.add_pixbuf_formats()
    btn.add_filter(f)
  
    f = gtk.FileFilter()
    f.set_name("All files")
    f.add_pattern("*")
    btn.add_filter(f)

    cbtn = gtk.Button()
    hbox.pack_start(cbtn, False)
    cbtn.connect("clicked", gui_file_unset_cb, btn)
    img = gtk.Image()
    cbtn.add(img)
    img.set_from_stock(gtk.STOCK_CLEAR, gtk.ICON_SIZE_MENU)
    log.debug("file btn ready")
    hbox.show_all()
    return hbox


def gui_scale_type_set_cb(cb):
    model = cb.get_model()
    index = cb.get_active()
    scale = model[index][1]
    log.debug("set scale type %s", scale)
    gui['th'].set_scale_type(scale)
    for w in gui['scale_value']:
        w.set_sensitive(scale == 'manual')
    

def gui_scale_ratio_set_cb(sb):
    value = sb.get_value()
    log.debug("set scale ratio %s", value)
    gui['th'].set_scale_ratio(value)
    glib.idle_add(gui_update_scale_ratio, sb)


def gui_update_scale_ratio(sb):
    value = sb.get_value()
    nvalue = gui['th'].get_scale_ratio()
    log.debug("cur value %s", nvalue)
    if value != nvalue:
        log.debug("update buton value %s, with real value %s",
                  value, nvalue)
        sb.set_value(nvalue)
             
    
def gui_scale_type_btn():
    log.debug("enter")

    # scales = ['fit', 'cover', 'auto', 'manual']
    scales = scale_types
    liststore = gtk.ListStore(str, str)
    for s in scales:
        liststore.append([s.title(), s])

    combobox = gtk.ComboBox(liststore)
    gui['scale'] = combobox
    try:
        ae = scales.index(args.scale)
    except:
        ae = 0
    combobox.set_active(ae)
    # gui_scale_set_cb(combobox)
    
    cell = gtk.CellRendererText()
    combobox.pack_start(cell, True)
    combobox.add_attribute(cell, 'text', 0)
    combobox.connect('changed', gui_scale_type_set_cb)

    return combobox


def gui_scale_ratio_btn():
    hbox = gtk.HBox(False, 5)
  
    a = gtk.Adjustment(value=0.2, lower=0.05, upper=20.0,
                       step_incr=0.01)
    sb = gtk.SpinButton(adjustment=a, climb_rate=0.0, digits=2)
    gui['scale_r'] = sb
    hbox.pack_start(sb, False)
    log.debug("scale ratio btn is ready")
    sb.connect("value-changed", gui_scale_ratio_set_cb)
    
    hbox.show_all()
    return hbox


def gui_scale_btn():
    log.debug("enter")
    hbox = gtk.HBox(False, 20)

    hbox.pack_start(gui_scale_type_btn(), False)
    hbox.pack_start(gui_scale_ratio_btn(), False)
    
    hbox.show_all()
    return hbox

def gui_gravity_set_cb(cb):
    model = cb.get_model()
    index = cb.get_active()
    gravity = model[index][1]
    log.debug("set gravity type %s", gravity)
    gui['th'].set_gravity_type(gravity)
    # gui['gravity_r'].set_sensitive(gravity == 'manual')
    


def gui_gravity_btn():
    log.debug("enter")
  
    # gravitys = ['fit', 'cover', 'auto', 'manual']
    gravitys = gravity_types
    liststore = gtk.ListStore(str, str)
    for s in gravitys:
        liststore.append([s.title(), s])

    combobox = gtk.ComboBox(liststore)
    gui['gravity'] = combobox
    try:
        ae = gravitys.index(args.gravity)
    except:
        ae = 0
    combobox.set_active(ae)
    # gui_gravity_set_cb(combobox)
    
    cell = gtk.CellRendererText()
    combobox.pack_start(cell, True)
    combobox.add_attribute(cell, 'text', 0)
    combobox.connect('changed', gui_gravity_set_cb)

    return combobox


def gui_color_set_cb(btn):
    c = btn.get_color()
    log.debug("set color %s", c)
    gui['th'].set_color(c)
    

def gui_color_btn():
    
    c = gtk.gdk.color_parse(args.color)
    btn = gtk.ColorButton(c)
    gui['color'] = btn
    btn.connect("color-set", gui_color_set_cb)
    gui['th'].set_color(c)
    
    return btn


def gui_run():
    log.debug("enter")
    w = gtk.Dialog("Set Wallpaper", None, 0,
            (gtk.STOCK_CLOSE, gtk.RESPONSE_REJECT,
             gtk.STOCK_APPLY, gtk.RESPONSE_ACCEPT))
    # w.get_action_area().set_layout(gtk.BUTTONBOX_CENTER)
    w.set_border_width(10)
    w.set_icon_name("background")
    w.set_default_size(650, 480)
    w.set_position(gtk.WIN_POS_CENTER)
    w.connect("delete-event", gui_exit_cb)
    w.connect("destroy", gui_exit_cb)
    # vbox = gtk.VBox(False, 4)
    # w.add(vbox)

    sratio = gtk.gdk.screen_width() / float(gtk.gdk.screen_height())
    frame = gtk.AspectFrame(ratio = sratio, obey_child = False)
    w.vbox.pack_start(frame, True, True, 0)
    frame.set_shadow_type(gtk.SHADOW_IN)
    frame.set_border_width(10)

    frame2 = gtk.AspectFrame(ratio = sratio, obey_child = False)
    frame.add(frame2)
    frame2.set_shadow_type(gtk.SHADOW_NONE)
    frame2.set_border_width(30)

    th = ThImage()
    gui['th'] = th
    th.drag_dest_set(gtk.DEST_DEFAULT_ALL,
            [("text/uri-list", 0, 11)],
            gtk.gdk.ACTION_COPY)
    th.connect("drag_data_received", gui_draged_cb)
    frame2.add(th)

    ali = gtk.Alignment(0.5, 0.0, 0, 0)
    w.vbox.pack_start(ali, False, True, 0)

    vbox = gtk.Table(4, 4)
    vbox.set_col_spacing(0, 10)
    vbox.set_col_spacing(2, 10)
    ali.add(vbox)

    def get_label(text):
        label = gtk.Label(text)
        label.set_alignment(1.0, 0.5)
        return label

    def get_widget(child):
        a = gtk.Alignment(0.0, 0.5, 0, 0)
        a.add(child)
        return a

    row = 0
    label = get_label("Image")
    vbox.attach(label, 0, 1, row, row + 1)
    widget = get_widget(gui_file_btn())
    vbox.attach(widget, 1, 4, row, row + 1)

    row += 1
    label = get_label("Color")
    vbox.attach(label, 0, 1, row, row + 1)
    widget = get_widget(gui_color_btn())
    vbox.attach(widget, 1, 2, row, row + 1)

    row += 1
    label = get_label("Scale")
    vbox.attach(label, 0, 1, row, row + 1)
    widget = get_widget(gui_scale_type_btn())
    vbox.attach(widget, 1, 2, row, row + 1)

    # label = get_label("Value")
    # vbox.attach(label, 0, 1, 2, 3)
    #             # 0, gtk.EXPAND|gtk.FILL)
    # widget = get_widget(gui_scale_ratio_btn())
    # vbox.attach(widget, 1, 2, 2, 3)

    label = get_label("Value")
    vbox.attach(label, 2, 3, row, row + 1)
                # 0, gtk.EXPAND|gtk.FILL)
    widget = get_widget(gui_scale_ratio_btn())
    vbox.attach(widget, 3, 4, row, row + 1)
    gui['scale_value'] = [label, widget]
    
    row += 1
    label = get_label("Gravity")
    vbox.attach(label, 0, 1, row, row + 1)
    widget = get_widget(gui_gravity_btn())
    vbox.attach(widget, 1, 2, row, row + 1)

    w.vbox.show_all()
    log.debug("========= init =========")
    if args.image:
        log.debug("set image %s", args.image)
        gui['image'].set_filename(args.image)
        gui_file_set_cb(gui['image'])

    
    log.debug("set scale type %s", args.scale)
    gui['scale'].set_active(scale_types.index(args.scale))
    gui_scale_type_set_cb(gui['scale'])

    log.debug("set scale ratio %s", args.scale_r)
    gui['scale_r'].set_value(args.scale_r)
    gui_scale_ratio_set_cb(gui['scale_r'])

    # vbox.pack_start(gui_file_btn(), False, True, 0)
    # vbox.pack_start(gui_scale_btn(), False, True, 0)
    # vbox.pack_start(gui_gravity_btn(), False, True, 0)
    # vbox.pack_start(gui_color_btn(), False, True, 0)
    # vbox.pack_start(gtk.Label(""), True, True, 10)

    w.vbox.show_all()
    # gui['th'].set_pix(args.image)
    gui['th'].set_color(args.color)
    # gui['th'].set_scale_type(args.scale)
    gui['th'].set_scale_ratio(args.scale_r)
    gui['th'].set_gravity_type(args.gravity)
    return w
   

############################################
# Main
############################################
conf_path = os.path.expanduser('~/.config/wallpaper')

def conf_load():
    try:
        c = json.loads(open(conf_path, 'r').read())
    except:
        c = {}
    log.debug("load conf %s", c)
    return c


def conf_save(c):
    log.debug("save conf %s", c)
    open(conf_path, 'w').write(json.dumps(c))


def conf_run(c):
    cmd = ['wallpaper']
    for opt in ['scale', 'color']:
        if c[opt]:
            cmd += ['--' + opt + '=' + c[opt]]
    if c['image']:
        cmd += [c['image']]
    log.debug("cmd %s", cmd)
    try:
        return sp.call(cmd)
    except OSError as e:
        msg = "Can't run '%s'\n%s" % (cmd[0], e.strerror)
        log.error("%s", msg)
        if 'top' in gui:
            d = gtk.MessageDialog(gui['top'],
                    gtk.DIALOG_MODAL | gtk.DIALOG_DESTROY_WITH_PARENT,
                    gtk.MESSAGE_ERROR,
                    gtk.BUTTONS_CLOSE,
                    msg)        
            d.run()
            d.destroy()
        return 1
    

def args_load():
    c = conf_load()
    for k in c:
        setattr(args, k, c[k])

    # sanity check
    if type(args.scale) == unicode:
        args.scale = str(args.scale)
    log.debug("type of scale %s", type(args.scale))
    if type(args.scale) != str or args.scale not in scale_types:
        log.warning("wrong scale type '%s' in conf", args.scale)
        args.scale = 'auto'


    if type(args.gravity) == unicode:
        args.gravity = str(args.gravity)
    log.debug("type of gravity %s", type(args.gravity))
    if type(args.gravity) != str or args.gravity not in gravity_types:
        log.warning("wrong gravity type '%s' in conf", args.gravity)
        args.gravity = 'center'

        
    log.debug("loaded args %s", args)


if __name__ == '__main__':
    log.debug("args %s", sys.argv)
    conf_dir = os.path.dirname(conf_path)
    if not os.path.exists(conf_dir):
        os.makedirs(conf_dir)
        
    if args.saved:
        c = conf_load()
        rc = conf_run(c)
        exit(rc)
    
    # when run without args, show preview of prev command
    if len(sys.argv) == 1 or (len(sys.argv) == 2 and args.debug):
        args_load()
  
    w = gui_run()
    gui['top'] = w
    while w.run() == gtk.RESPONSE_ACCEPT:
        c = gui['th'].get_conf()
        log.debug("conf %s", c)
        conf_save(c)
        rc = conf_run(c)
        # exit(rc)
        
    w.destroy()




