#!/usr/bin/python2

############################################
# Imports
############################################
import logging
import argparse
import subprocess as sp
import os, sys
import json
import gtk, glib
import urlparse, urllib

#import threading
#import time
#import json
#import gtk, glib
#import signal


############################################
# Logging
############################################

# log = logging.getLogger(__name__)
log = logging.getLogger()

def _init_log():
    FORMAT = '%(module)s %(funcName)s:%(lineno)d %(message)s'
    # logging.basicConfig(format=FORMAT)
    log.setLevel(logging.INFO)
    # log.setLevel(logging.DEBUG)
    h = logging.StreamHandler()
    # f = MyFormatter()
    f = logging.Formatter(FORMAT)
    h.setFormatter(f)
    log.addHandler(h)

_init_log()

############################################
# Argument parsing
############################################
scale_types = ['fit', 'cover', 'auto', 'manual']
gravity_types = ['center', 'north', 'east', 'south', 'west']

desc = '''Wallpaper configurator'''
p = argparse.ArgumentParser(description=desc)
p.add_argument("--debug", help="debug mode", action="store_true")
p.add_argument("--scale", help="scale type: " + ','.join(scale_types) + \
               "(default %(default)s)",
    choices=scale_types, default='auto')
p.add_argument("--gravity", help="gravity type: " + ','.join(gravity_types) + \
               "(default %(default)s)",
    choices=gravity_types, default='center')
p.add_argument("--scale-r", help="scale ration, default %(default)s",
               metavar='ratio', default=1.0)
p.add_argument("--offset", help="offset, default %(default)s",
               metavar='ratio', type=int, default=0)
p.add_argument("--color", help="fill color, name or '#RRGGBB' value (default %(default)s)",
    default='#ffd2ac')
p.add_argument("--saved", help="apply saved configuration (if any) and exit",
    action='store_true')

p.add_argument("image", help="image", nargs='?')


args = p.parse_args()
if args.debug:
    log.setLevel(logging.DEBUG)

log.debug("Args: %s", args)

############################################
# Misc
############################################
def die(msg, ret = 1):
    print >> sys.stderr, msg
    exit(ret)

############################################
# Thumbnail Image
############################################

def get_geom(
        base_ratio, base_width, base_height,
        ovr_ratio, ovr_width, ovr_height,
        scale_type, scale_ratio,
        gravity, offset):

    log.debug("==[ Params ]==")
    log.debug("ratio: base %s, pix %s", base_ratio, ovr_ratio)
    log.debug("scale: type %s, ratio %s", scale_type, scale_ratio)
    log.debug("base: size %d x %d", base_width, base_height)
    log.debug("pix: size %d x %d", ovr_width, ovr_height)
    log.debug("gravity:  %s", gravity)
    log.debug("offset:  %s", offset)
        
    if scale_type == 'auto':
        diff = abs(base_ratio - ovr_ratio)
        log.debug("diff ratio %.2f", diff)
        if diff < 0.55:
            scale_type_real = 'cover'
        else:
            scale_type_real = 'fit'
    else:
        scale_type_real = scale_type

    if scale_type_real == 'cover':
        scale_ratio = max(float(base_width) / ovr_width,
                          float(base_height) / ovr_height)
    elif scale_type_real == 'fit':
        scale_ratio = min(float(base_width) / ovr_width,
                          float(base_height) / ovr_height)
    elif scale_type_real == 'manual':
        if scale_ratio <= 0.0:
            scale_ratio = 0.05
    else:
        scale_ratio = 0.2


    log.debug("scale: type %s, ratio %.2f", scale_type_real, scale_ratio)
    dest_width  = max(10, ovr_width * scale_ratio)
    dest_height = max(10, ovr_height * scale_ratio)
    if scale_type_real == 'manual':
        while True:
            log.debug("dest size %s x %s", dest_width, dest_height)

            if dest_width < 3000 and dest_height < 3000:
                break
            scale_ratio -= 0.05
            if scale_ratio <= 0:
                break
            dest_width  = max(10, ovr_width * scale_ratio)
            dest_height = max(10, ovr_height * scale_ratio)
                
    if scale_ratio <= 0.0:
        scale_ratio = 0.05
    log.debug("dest size: %d x %d", dest_width, dest_height)
    dest_x = 0
    dest_y = 0
    offset_x = (base_width - dest_width) / 2
    offset_y = (base_height - dest_height) / 2
    log.debug("offset %d %d", offset_x, offset_y)

    if scale_type_real in ['fit', 'cover']:
        gravity = 'center'
    log.debug("final gravity %s", gravity)

    if scale_type_real != 'manual' or gravity == 'center':
        offset = 0
    log.debug("final offset %s", offset)
    
    if gravity == 'center':
        if offset_x > 0:
            dest_x = offset_x
        if offset_y > 0:
            dest_y = offset_y

    elif gravity == 'north':
        if offset_x > 0:
            dest_x = offset_x
        dest_y = offset
        offset_y = offset

    elif gravity == 'south':
        if offset_x > 0:
            dest_x = offset_x
        if offset_y > 0:
            offset_y = offset_y * 2 - offset
            dest_y = offset_y
      
    elif gravity == 'west':
        if offset_y > 0:
            dest_y = offset_y
        dest_x = offset
        offset_x = offset
        
  
    elif gravity == 'east':
        if offset_y > 0:
            dest_y = offset_y
        if offset_x > 0:
            offset_x = offset_x * 2 - offset    
            dest_x = offset_x
      

        
            
    log.debug("dest pos %+d %+d", dest_x, dest_y)
    log.debug("offset %+d %+d", int(offset_x), int(offset_y))
    if dest_width > base_width:
        dest_width = base_width
    if dest_height > base_height:
        dest_height = base_height
    log.debug("dest geom=%dx%d pos=%dx%d",
        dest_width, dest_height, dest_x, dest_y)

    dest_x = int(dest_x)
    dest_y = int(dest_y)
    dest_width = int(dest_width)
    dest_height = int(dest_height)
    offset_x = int(offset_x)
    offset_y = int(offset_y)
    log.debug("dest: %d,%d %d x%d", dest_x, dest_y, dest_width, dest_height)
    log.debug("offset: %d,%d, scale: type %s, ratio %s",
              offset_x, offset_y, scale_type_real, scale_ratio)
    return (dest_x, dest_y, dest_width, dest_height,
            offset_x, offset_y, scale_type_real, scale_ratio)


def paint_base__pix(base_pix, rgba, ovr_pix,
                scale, scale_ratio, gravity, offset):

    log.debug("params: base_pix %s, rgba %x, ovr_pix %s",
              base_pix, rgba, ovr_pix)
    log.debug("params: scale %s, ratio %s, gravity %s, offset %s",
              scale, scale_ratio, gravity, offset)
    base_pix.fill(rgba)
    if not ovr_pix:
        return
    
    base_width = base_pix.get_width()
    base_height = base_pix.get_height()
    base_ratio = 1.0 * base_width / base_height

    ovr_width = ovr_pix.get_width()
    ovr_height = ovr_pix.get_height()
    ovr_ration = 1.0 * ovr_width / ovr_height

    t = get_geom(base_ratio, base_width, base_height,
                 ovr_ration, ovr_width, ovr_height,
                 scale, scale_ratio, gravity, offset)
    dest_x, dest_y, dest_width, dest_height, offset_x, \
        offset_y, scale_real, scale_ratio = t
    ovr_pix.composite(base_pix,
                      dest_x, dest_y, dest_width, dest_height,
                      offset_x, offset_y, scale_ratio, scale_ratio,
                      gtk.gdk.INTERP_HYPER, 255)

    
def color_to_rgba(color):
    c = gtk.gdk.color_parse(color)
    rgba = ((c.red >> 8) << 24) | ((c.green >> 8) << 16) | ((c.blue >> 8) << 8)
    # rgba = 0xffd2ac00
    log.debug("rgba %x", rgba)
    return rgba

        
class ThImage(gtk.Image):
  
    def __init__(self):
        gtk.Image.__init__(self)
        self.connect("expose_event", self._expose)
        self.connect("size_allocate", self._size_alloc)
        self.pix = None
        self.ipix = None
        self.color = None
        self.uri = None
        self.idle_id = None
        self.scale = 'auto'
        self.scale_real = None
        self.scale_r = 1.0
        self.scale_factor = 0.5
        self.gravity = 'center'
        self.offset = 0
        self.set_color("#ffd2ac")
        self.sratio = gtk.gdk.screen_width() / float(gtk.gdk.screen_height())

        
    def set_pix(self, uri):
        log.debug("uri %s", uri)
        self.uri = None
        self.ipix = None
        self._update_pix()
        
        if not uri:
            return None
        
        if uri.startswith('file://'):
            uri = urllib.url2pathname(uri[7:])
        elif uri[0] == '/':
            pass
        else:
            log.warning("not a path %s", uri)
            return None
      
        try:
            self.ipix = gtk.gdk.pixbuf_new_from_file(uri)
            self.uri = uri
            return uri
        except:
            return None


    def set_color(self, color):
        log.debug("color %s", color)
        self.color = str(color)
        self.rgba = color_to_rgba(self.color)
        self._update_pix()

        
    def set_gravity_type(self, gravity):
        log.debug("gravity %s", gravity)
        if not gravity in gravity_types:
            log.warning("unsupported gravity %s", gravity)
            return
        self.gravity = gravity
        self._update_pix()

        
    def set_offset(self, offset):
        log.debug("offset %s", offset)
        self.offset = offset
        self._update_pix()

        
    def get_offset(self):
        return self.offset
    

    def get_scale_type(self):
        return self.scale

    
    def set_scale_type(self, scale):
        log.debug("scale %s", scale)
        if not scale in scale_types:
            log.warning("unsupported scale %s", scale)
            return
        self.scale = scale
        self._update_pix()

        
    def set_scale_ratio(self, scale_r):
        log.debug("scale ratio %s", scale_r)
        if self.scale == 'manual':
            log.debug("accepted")
            self.scale_r = scale_r
        self._update_pix()

        
    def get_scale_ratio(self):
        return self.scale_r
    
        
    def get_conf(self):
        c = {
            'scale': self.scale,
            'scale_r': self.scale_r,
            'color': self.color,
            'image': self.uri,
            'gravity': self.gravity,
            'offset': self.offset,
        }
        return c
    
    def _expose(self, widget, event):
        a = event.area
        log.debug("ev %s, pix %s", a, self.pix)
        if not self.pix:
            self._update_pix()
        else:
            self.window.draw_pixbuf(self.style.black_gc, self.pix, 0, 0, a.x, a.y)


    def _size_alloc(self, widget, a):
        self.scale_factor = float(a.width) / gtk.gdk.screen_width()
        log.debug("alloc %s, scale factor %s", a, self.scale_factor)
        self.pix = None
        self._update_pix()


    def _update_pix(self):
        log.debug("idle %s", self.idle_id)
        if self.idle_id:
            return
        self.idle_id = glib.idle_add(self._update_pix_real)

        
    def _update_pix_real(self):
        a = self.get_allocation()
        log.debug("a %s", a)
        self.pix = gtk.gdk.Pixbuf(gtk.gdk.COLORSPACE_RGB, False,
            8, a.width, a.height)
        paint_base__pix(self.pix, self.rgba, self.ipix,
                        self.scale, self.scale_r * self.scale_factor,
                        self.gravity, self.offset * self.scale_factor)

        self.queue_draw()
        self.idle_id = None
        return False


    def apply_conf(self):
        log.debug("======= apply conf =====")
        bw = gtk.gdk.screen_width()
        bh = gtk.gdk.screen_height()
        base_pix = gtk.gdk.Pixbuf(gtk.gdk.COLORSPACE_RGB, False, 8, bw, bh)
        paint_base__pix(base_pix, self.rgba, self.ipix,
                        self.scale, self.scale_r, self.gravity, self.offset)


        return base_pix
        
        


############################################
# GUI
############################################

gui = {}

def gui_exit_cb(x=None, y=None):
    exit(0)



    
def gui_draged_cb(widget, drag_context, x, y, selection, info, time):
    uri = selection.data.split()[0]
    uri = gui['th'].set_pix(uri)
    log.debug("set to %s", uri)
    gui['image'].unselect_all()
    if uri:
        gui['image'].set_filename(uri)
    

def gui_file_set_cb(btn):
    path = btn.get_filename()
    log.debug("path %s", path)
    uri = gui['th'].set_pix(path)
    log.debug("set to %s", uri)
    gui['image'].unselect_all()
    if uri:
        gui['image'].set_filename(uri)
            

    
def gui_file_unset_cb(cbtn, btn):
    log.debug("")
    btn.unselect_all()
    gui['th'].set_pix(None)
    
    
def gui_file_btn():
    hbox = gtk.HBox(False, 3)
 
    btn = gtk.FileChooserButton('Select a File')
    gui['image'] = btn
    hbox.pack_start(btn, False)
    btn.connect("file-set", gui_file_set_cb)
    btn.set_width_chars(20)
  

    f = gtk.FileFilter()
    f.set_name("Images")
    f.add_pixbuf_formats()
    btn.add_filter(f)
  
    f = gtk.FileFilter()
    f.set_name("All files")
    f.add_pattern("*")
    btn.add_filter(f)

    cbtn = gtk.Button()
    hbox.pack_start(cbtn, False)
    cbtn.connect("clicked", gui_file_unset_cb, btn)
    img = gtk.Image()
    cbtn.add(img)
    img.set_from_stock(gtk.STOCK_CLEAR, gtk.ICON_SIZE_MENU)
    log.debug("file btn ready")
    hbox.show_all()
    return hbox


def gui_scale_type_set_cb(cb):
    model = cb.get_model()
    index = cb.get_active()
    scale = model[index][1]
    log.debug("set scale type %s", scale)
    gui['th'].set_scale_type(scale)
    glib.idle_add(gui_update_all)
    # for w in gui['scale_ratio_widgets']:
    #     w.set_sensitive(scale == 'manual')
    # for w in gui['gravity_widgets']:
    #     w.set_sensitive(scale == 'manual')
    # for w in gui['offset_widgets']:
    #     w.set_sensitive(scale == 'manual')
    

def gui_scale_ratio_set_cb(sb):
    value = sb.get_value()
    log.debug("set scale ratio %s", value)
    gui['th'].set_scale_ratio(value)
    glib.idle_add(gui_update_all)


def gui_scale_type_btn():
    log.debug("enter")

    # scales = ['fit', 'cover', 'auto', 'manual']
    scales = scale_types
    liststore = gtk.ListStore(str, str)
    for s in scales:
        liststore.append([s.title(), s])

    combobox = gtk.ComboBox(liststore)
    gui['scale'] = combobox
    try:
        ae = scales.index(args.scale)
    except:
        ae = 0
    combobox.set_active(ae)
    # gui_scale_set_cb(combobox)
    
    cell = gtk.CellRendererText()
    combobox.pack_start(cell, True)
    combobox.add_attribute(cell, 'text', 0)
    combobox.connect('changed', gui_scale_type_set_cb)

    return combobox


def gui_scale_ratio_btn():
    hbox = gtk.HBox(False, 5)
  
    a = gtk.Adjustment(value=0.2, lower=0.05, upper=20.0,
                       step_incr=0.01)
    sb = gtk.SpinButton(adjustment=a, climb_rate=0.0, digits=2)
    gui['scale_r'] = sb
    hbox.pack_start(sb, False)
    log.debug("scale ratio btn is ready")
    sb.connect("value-changed", gui_scale_ratio_set_cb)
    
    hbox.show_all()
    return hbox


def gui_scale_btn():
    log.debug("enter")
    hbox = gtk.HBox(False, 20)

    hbox.pack_start(gui_scale_type_btn(), False)
    hbox.pack_start(gui_scale_ratio_btn(), False)
    
    hbox.show_all()
    return hbox

def gui_gravity_set_cb(cb):
    model = cb.get_model()
    index = cb.get_active()
    gravity = model[index][1]
    log.debug("set gravity type %s", gravity)
    gui['th'].set_gravity_type(gravity)
    glib.idle_add(gui_update_all)

    # gui['gravity'].set_sensitive(gravity == 'manual')
    # for w in gui['offset_widgets']:
    #     w.set_sensitive(gravity != 'center')
    
    

def gui_gravity_btn():
    log.debug("enter")
  
    # gravitys = ['fit', 'cover', 'auto', 'manual']
    gravitys = gravity_types
    liststore = gtk.ListStore(str, str)
    for s in gravitys:
        liststore.append([s.title(), s])

    combobox = gtk.ComboBox(liststore)
    gui['gravity'] = combobox
    try:
        ae = gravitys.index(args.gravity)
    except:
        ae = 0
    combobox.set_active(ae)
    # gui_gravity_set_cb(combobox)
    
    cell = gtk.CellRendererText()
    combobox.pack_start(cell, True)
    combobox.add_attribute(cell, 'text', 0)
    combobox.connect('changed', gui_gravity_set_cb)

    return combobox



def gui_offset_set_cb(sb):
    value = sb.get_value()
    log.debug("set scale ratio %s", value)
    gui['th'].set_offset(value)
    glib.idle_add(gui_update_all)


def gui_offset_btn():
    a = gtk.Adjustment(value=0.0, lower=0.0, upper=320.0,
                       step_incr=2.0)
    sb = gtk.SpinButton(adjustment=a, climb_rate=0.0, digits=0)
    gui['offset'] = sb
    sb.connect("value-changed", gui_offset_set_cb)
    
    sb.show_all()
    return sb

def gui_color_set_cb(btn):
    c = btn.get_color()
    log.debug("set color %s", c)
    gui['th'].set_color(c)
    

def gui_color_btn():
    
    c = gtk.gdk.color_parse(args.color)
    btn = gtk.ColorButton(c)
    gui['color'] = btn
    btn.connect("color-set", gui_color_set_cb)
    gui['th'].set_color(c)
    
    return btn

        
def gui_update_all():
    c = gui['th'].get_conf()
    log.debug("cur conf %s", json.dumps(c, indent=4))

    scale = gui['th'].get_scale_type()
    cb = gui['scale']
    model = cb.get_model()
    index = cb.get_active()
    value = model[index][1]
    log.debug("scale type: th %s, gui %s", scale, value)
    if value != scale:
        log.debug("update scale type to  %s", scale)
        cb.set_active(scale_types.index(scale))
        # gui_scale_type_set_cb(cb)
    state = (value == 'manual')
    for w in gui['scale_ratio_widgets']:
        w.set_sensitive(state)
    for w in gui['gravity_widgets']:
        w.set_sensitive(state)
        

    sb = gui['scale_r']
    value = sb.get_value()
    log.debug("scale ratio: cur %s", value)
    if value != c['scale_r']:
        log.debug("update scale ratio to  %s", c['scale_r'])
        sb.set_value(value)
        # gui_scale_ratio_set_cb(sb)

    cb = gui['gravity']
    model = cb.get_model()
    index = cb.get_active()
    value = model[index][1]
    log.debug("gravity: cur %s", value)
    if value != c['gravity']:
        log.debug("update gravity type to  %s", c['gravity'])
        cb.set_active(gravity_types.index(c['gravity']))
        # gui_gravity_type_set_cb(cb)
    log.debug("gravity sensitivuty %s", cb.is_sensitive())
    state = cb.is_sensitive() and value != 'center'
    for w in gui['offset_widgets']:
        w.set_sensitive(state)
        
        
    sb = gui['offset']
    value = sb.get_value()
    log.debug("offset: cur %s", value)
    if value != c['offset']:
        log.debug("update offset to  %s", c['offset'])
        sb.set_value(value)
        # gui_offsetatio_set_cb(sb)

        

def gui_run():
    log.debug("enter")
    w = gtk.Dialog("Set Wallpaper", None, 0,
            (gtk.STOCK_CLOSE, gtk.RESPONSE_REJECT,
             gtk.STOCK_APPLY, gtk.RESPONSE_ACCEPT))
    # w.get_action_area().set_layout(gtk.BUTTONBOX_CENTER)
    w.set_border_width(10)
    w.set_icon_name("background")
    w.set_default_size(650, 480)
    w.set_position(gtk.WIN_POS_CENTER)
    w.connect("delete-event", gui_exit_cb)
    w.connect("destroy", gui_exit_cb)
    # vbox = gtk.VBox(False, 4)
    # w.add(vbox)

    sratio = gtk.gdk.screen_width() / float(gtk.gdk.screen_height())
    frame = gtk.AspectFrame(ratio = sratio, obey_child = False)
    w.vbox.pack_start(frame, True, True, 0)
    frame.set_shadow_type(gtk.SHADOW_IN)
    frame.set_border_width(10)

    frame2 = gtk.AspectFrame(ratio = sratio, obey_child = False)
    frame.add(frame2)
    frame2.set_shadow_type(gtk.SHADOW_NONE)
    frame2.set_border_width(30)

    th = ThImage()
    gui['th'] = th
    th.drag_dest_set(gtk.DEST_DEFAULT_ALL,
            [("text/uri-list", 0, 11)],
            gtk.gdk.ACTION_COPY)
    th.connect("drag_data_received", gui_draged_cb)
    frame2.add(th)

    ali = gtk.Alignment(0.5, 0.0, 0, 0)
    w.vbox.pack_start(ali, False, True, 0)

    vbox = gtk.Table(4, 4)
    vbox.set_col_spacing(0, 10)
    vbox.set_col_spacing(2, 10)
    ali.add(vbox)

    def get_label(text):
        label = gtk.Label(text)
        label.set_alignment(1.0, 0.5)
        return label

    def get_widget(child):
        a = gtk.Alignment(0.0, 0.5, 0, 0)
        a.add(child)
        return a

    row = 0
    label = get_label("Image")
    vbox.attach(label, 0, 1, row, row + 1)
    widget = get_widget(gui_file_btn())
    vbox.attach(widget, 1, 4, row, row + 1)

    row += 1
    label = get_label("Color")
    vbox.attach(label, 0, 1, row, row + 1)
    widget = get_widget(gui_color_btn())
    vbox.attach(widget, 1, 2, row, row + 1)

    row += 1
    label = get_label("Scale")
    vbox.attach(label, 0, 1, row, row + 1)
    widget = get_widget(gui_scale_type_btn())
    vbox.attach(widget, 1, 2, row, row + 1)

    # label = get_label("Value")
    # vbox.attach(label, 0, 1, 2, 3)
    #             # 0, gtk.EXPAND|gtk.FILL)
    # widget = get_widget(gui_scale_ratio_btn())
    # vbox.attach(widget, 1, 2, 2, 3)

    label = get_label("Value")
    vbox.attach(label, 2, 3, row, row + 1)
                # 0, gtk.EXPAND|gtk.FILL)
    widget = get_widget(gui_scale_ratio_btn())
    vbox.attach(widget, 3, 4, row, row + 1)
    gui['scale_ratio_widgets'] = [label, widget]
    
    row += 1
    label = get_label("Gravity")
    vbox.attach(label, 0, 1, row, row + 1)
    widget = get_widget(gui_gravity_btn())
    vbox.attach(widget, 1, 2, row, row + 1)
    gui['gravity_widgets'] = [label, widget]
    
    label = get_label("Offset")
    vbox.attach(label, 2, 3, row, row + 1)
    widget = get_widget(gui_offset_btn())
    vbox.attach(widget, 3, 4, row, row + 1)
    gui['offset_widgets'] = [label, widget]
    
    w.vbox.show_all()
    log.debug("========= init =========")
    if args.image:
        log.debug("set image %s", args.image)
        gui['image'].set_filename(args.image)
        gui_file_set_cb(gui['image'])

    
    log.debug("set scale type %s", args.scale)
    gui['scale'].set_active(scale_types.index(args.scale))
    gui_scale_type_set_cb(gui['scale'])

    log.debug("set scale ratio %s", args.scale_r)
    gui['scale_r'].set_value(args.scale_r)
    gui_scale_ratio_set_cb(gui['scale_r'])

    log.debug("set gravity %s", args.gravity)
    gui['gravity'].set_active(gravity_types.index(args.gravity))
    gui_gravity_set_cb(gui['gravity'])

    log.debug("set offset %s", args.offset)
    gui['offset'].set_value(args.offset)
    gui_offset_set_cb(gui['offset'])

    # vbox.pack_start(gui_file_btn(), False, True, 0)
    # vbox.pack_start(gui_scale_btn(), False, True, 0)
    # vbox.pack_start(gui_gravity_btn(), False, True, 0)
    # vbox.pack_start(gui_color_btn(), False, True, 0)
    # vbox.pack_start(gtk.Label(""), True, True, 10)

    w.vbox.show_all()
    # gui['th'].set_pix(args.image)
    gui['th'].set_color(args.color)
    # gui['th'].set_scale_type(args.scale)
    gui['th'].set_scale_ratio(args.scale_r)
    gui['th'].set_gravity_type(args.gravity)
    return w
   

############################################
# Main
############################################
conf_path = os.path.expanduser('~/.config/wallpaper')

def conf_load():
    try:
        c = json.loads(open(conf_path, 'r').read())
    except:
        c = {}
    log.debug("load conf %s", c)
    return c


def conf_save(c):
    log.debug("save conf %s", c)
    open(conf_path, 'w').write(json.dumps(c))



def conf_run(c):
    log.debug("======= apply conf =====")
    bw = gtk.gdk.screen_width()
    bh = gtk.gdk.screen_height()
    base_pix = gtk.gdk.Pixbuf(gtk.gdk.COLORSPACE_RGB, False, 8, bw, bh)

    try:
        ovr_pix = gtk.gdk.pixbuf_new_from_file(c['image'])
    except:
        ovr_pix = None
    rgba = color_to_rgba(c['color'])
    paint_base__pix(base_pix, rgba, ovr_pix,
                    c['scale'], c['scale_r'], c['gravity'],
                    c['offset'])


    name = "/tmp/wallpaper-tmp.png"
    base_pix.save(name, "png")
    cmd = ['wallpaper', name]
    log.debug("cmd %s", cmd)
    try:
        return sp.call(cmd)
    except OSError as e:
        msg = "Can't run '%s'\n%s" % (cmd[0], e.strerror)
        log.error("%s", msg)
        if 'top' in gui:
            d = gtk.MessageDialog(gui['top'],
                    gtk.DIALOG_MODAL | gtk.DIALOG_DESTROY_WITH_PARENT,
                    gtk.MESSAGE_ERROR,
                    gtk.BUTTONS_CLOSE,
                    msg)        
            d.run()
            d.destroy()
    finally:
        # os.remove(name)
        pass
        
        

def args_load():
    c = conf_load()
    for k in c:
        setattr(args, k, c[k])

    # sanity check
    if type(args.scale) == unicode:
        args.scale = str(args.scale)
    log.debug("type of scale %s", type(args.scale))
    if type(args.scale) != str or args.scale not in scale_types:
        log.warning("wrong scale type '%s' in conf", args.scale)
        args.scale = 'auto'


    if type(args.gravity) == unicode:
        args.gravity = str(args.gravity)
    log.debug("type of gravity %s", type(args.gravity))
    if type(args.gravity) != str or args.gravity not in gravity_types:
        log.warning("wrong gravity type '%s' in conf", args.gravity)
        args.gravity = 'center'

        
    log.debug("loaded args %s", args)


if __name__ == '__main__':
    log.debug("args %s", sys.argv)
    conf_dir = os.path.dirname(conf_path)
    if not os.path.exists(conf_dir):
        os.makedirs(conf_dir)
        
    if args.saved:
        c = conf_load()
        rc = conf_run(c)
        exit(rc)
    
    # when run without args, show preview of prev command
    if len(sys.argv) == 1 or (len(sys.argv) == 2 and args.debug):
        args_load()
  
    w = gui_run()
    gui['top'] = w
    while w.run() == gtk.RESPONSE_ACCEPT:
        c = gui['th'].get_conf()
        log.debug("conf %s", c)
        conf_save(c)
        rc = conf_run(c)
        # exit(rc)
        
    w.destroy()




